// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCnzj9UU23p6dwMo93lP09pRch8xLaToM',
    appId: '1:218607312023:web:de0aedba09bfea5e1b1dd2',
    messagingSenderId: '218607312023',
    projectId: 'peretemuan3',
    authDomain: 'peretemuan3.firebaseapp.com',
    storageBucket: 'peretemuan3.firebasestorage.app',
    measurementId: 'G-6RLG5VR5M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0MOy6UaSvTehRRb7XL07bexDpeaLER8',
    appId: '1:218607312023:android:34d0dcd4911eb21b1b1dd2',
    messagingSenderId: '218607312023',
    projectId: 'peretemuan3',
    storageBucket: 'peretemuan3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSkwtt8XcBqi6vA4RadzEJ9-TuRD7R6jE',
    appId: '1:218607312023:ios:a229e3d9e389d6211b1dd2',
    messagingSenderId: '218607312023',
    projectId: 'peretemuan3',
    storageBucket: 'peretemuan3.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSkwtt8XcBqi6vA4RadzEJ9-TuRD7R6jE',
    appId: '1:218607312023:ios:a229e3d9e389d6211b1dd2',
    messagingSenderId: '218607312023',
    projectId: 'peretemuan3',
    storageBucket: 'peretemuan3.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCnzj9UU23p6dwMo93lP09pRch8xLaToM',
    appId: '1:218607312023:web:b6c7cdd334700e901b1dd2',
    messagingSenderId: '218607312023',
    projectId: 'peretemuan3',
    authDomain: 'peretemuan3.firebaseapp.com',
    storageBucket: 'peretemuan3.firebasestorage.app',
    measurementId: 'G-1BKDRTKZ18',
  );
}
